name: Python CD

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Package Application
      run: |
        echo "# Calculadora Python" > README.md
        echo "Uma calculadora com funções básicas e avançadas" >> README.md
        zip -r calculadora.zip *.py README.md
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        files: |
          calculadora.zip
        body: |
          # Calculadora Python ${{ github.ref_name }}
          
          Calculadora com operações básicas e avançadas.
          
          ## Funcionalidades
          - Operações básicas: soma, subtração, multiplicação, divisão
          - Operações avançadas: potência, raiz quadrada, fatorial
